apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      imagePullSecrets:
      - name: oracle-registry-secret  # Reference to your secret
      containers:
      - name: mysql-operator
        image: container-registry.oracle.com/mysql/enterprise-operator:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: admin-password
