apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysqldemo1  
  namespace: mysql  
spec:
  secretName: mysql-secret  
  tlsUseSelfSigned: true  
  instances: 3  
  router:
    instances: 1  
